# Generated by Django 5.2 on 2025-04-09 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meiari_v1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workgroupticket',
            name='work_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='meiari_v1.workgroup'),
        ),
    ]
