# Generated by Django 5.2 on 2025-04-09 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meiari_v1', '0002_workgroupticket_work_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='workgroupticket',
            name='ticket_owner_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='meiari_v1.meiariuser'),
        ),
        migrations.AddField(
            model_name='workgroupticket',
            name='user_id',
            field=models.ManyToManyField(blank=True, related_name='tickets', to='meiari_v1.meiariuser'),
        ),
    ]
