# Generated by Django 5.2 on 2025-04-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meiari_v1', '0003_workgroupticket_ticket_owner_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workgroupticket',
            name='ticket_status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Verified', 'Verified'), ('Signed', 'Signed')], max_length=50),
        ),
    ]
