# Generated by Django 5.2 on 2025-04-10 18:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meiari_v1', '0004_alter_workgroupticket_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workgroupticket',
            name='ticket_status',
            field=models.CharField(choices=[('Created', 'Created'), ('Completed', 'Completed'), ('Verified', 'Verified'), ('Signed', 'Signed')], max_length=50),
        ),
        migrations.CreateModel(
            name='ReportRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('department_name', models.CharField(max_length=255)),
                ('sub_department_name', models.CharField(max_length=255)),
                ('access_id', models.CharField(max_length=50)),
                ('file_path', models.CharField(max_length=500)),
                ('ticket_status_type', models.CharField(choices=[('Created', 'Created'), ('Completed', 'Completed'), ('Verified', 'Verified'), ('Signed', 'Signed')], default='Created', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sub_dept_office_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meiari_v1.subdeptofficedetails')),
            ],
        ),
    ]
